name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest! Please ask your question below.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I would like to know...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background for your question.
      placeholder: Additional context...
    validations:
      required: false
  - type: textarea
    id: research
    attributes:
      label: What have you tried?
      description: Have you already looked at documentation or tried anything?
      placeholder: I have already tried...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
